using Nop.Core.Plugins;
using Nop.Services.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AF.Nop.Plugins.RssFeed
{
    public static class RssFeedLocales
    {
        public static void Install(BasePlugin plugin)
        {
            foreach (var d in Collection)
            {
                plugin.AddOrUpdatePluginLocaleResource(d.Key, d.Value);
            }
        }

        public static void Uninstall(BasePlugin plugin)
        {
            foreach (var d in Collection)
            {
                plugin.DeletePluginLocaleResource(d.Key);
            }
        }

        public static Dictionary<string, string> Collection
        {
            get
            {
                var list = new Dictionary<string, string>()
                {
                    {"AF.RssFeed.EnabledSchedule", "Enabled Schedule"},
                    {"AF.RssFeed.EnabledSchedule.Hint", "Enable or disable generating Rss feed on a schedual task"},
                    {"AF.RssFeed.TaskId", "Task Id"},
                    {"AF.RssFeed.TaskId.Hint", "The id of the schedule task. This value is generated by the system and MUST NOT be altered"},
                    {"AF.RssFeed.TaskName", "Task Name"},
                    {"AF.RssFeed.TaskName.Hint", "The name of the taks in the schedule table."},
                    {"AF.RssFeed.TaskRunTime", "Task Run Time"},
                    {"AF.RssFeed.TaskRunTime.Hint", "The time (approximately) to generate the XML file every day when the schedule is enabled."},
                    {"AF.RssFeed.TaskCheckTime", "Task Check Time"},
                    {"AF.RssFeed.TaskCheckTime.Hint", "The time in seconds to check if it's the time to generate the XML file or not. But at the end, the task will just run once a day."},
                    {"AF.RssFeed.LastRunTime", "Last Run Time"},
                    {"AF.RssFeed.LastRunTime.Hint", "The time of the last execution."},
                    { "AF.RssFeed.Title", "Title"},
                    {"AF.RssFeed.Title.Hint", "The name of the channel."},
                    { "AF.RssFeed.Link", "Link"},
                    {"AF.RssFeed.Title.Link", "The URL to the HTML website corresponding to the channel."},
                    { "AF.RssFeed.FileName", "FileName"},
                    {"AF.RssFeed.Title.FileName", "The file name that will be used to save the feed, ex: products-tr.xml"},
                    { "AF.RssFeed.Description", "Description"},
                    {"AF.RssFeed.Title.Description", "Phrase or sentence describing the channel."},
                    { "AF.RssFeed.Link.Hint", "The full url to be included in the XML file as channel link"},
                    { "AF.RssFeed.FileName.Hint", "The file name to save the generated XML file"},
                    { "AF.RssFeed.Description.Hint", "A summary about the channel"},

                    {"AF.RssFeed.GenerateNow", "Generate The Files Now"}
                };
                return list;
            }
        }
    }
}
